Modify commit hook to tell user how to override pre commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -40,7 +40,9 @@ check_file_size()
         s=$(git cat-file -s "$h")
         if [ "$s" -gt $hard_limit ]
         then
-            env echo -E 1>&2 "ERROR: hard size limit ($hard_limit) exceeded: $munged_filename ($s)\nrun git commit -n if you want to override me!"
+            env echo -E 1>&2 "ERROR: hard size limit ($hard_limit) exceeded: $munged_filename ($s)"
+            env echo -E 1>&2 "you can override me by running: git commit -n"
+
             n=$((n+1))
         elif [ "$s" -gt $soft_limit ]
         then
